//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaUPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ejemplar
    {
        public int idLibro { get; set; }
        public string edicion { get; set; }
        public System.DateTime anyoPublicacion { get; set; }
        public string estado { get; set; }
    
        public virtual Libro Libros { get; set; }
    }
}
